name: "build"

on:
  push:
    branches:
      - master

jobs:
  build-macos-arm:
    needs: test-rust
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Install dependencies
        run: |
          brew install node
          npm install -g pnpm

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build the app
        run: |
          cd src-tauri
          cp .env.example .env
          cargo tauri build --target aarch64-apple-darwin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-tasks.app
          path: src-tauri/target/release/bundle/macos/my-tasks.app 